se nocp


cal plug#begin()
Plug 'dense-analysis/ale'
Plug 'huyvohcmc/atlas.vim'
Plug 'ayu-theme/ayu-vim'
"Plug 'python/black', {'for': ['python']}
Plug 'ilyachur/cmake4vim'
Plug 'neoclide/coc-java'
"Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'lilydjwg/colorizer'
Plug 'whonore/Coqtail'
Plug 'Raimondi/delimitMate'
Plug 'mattn/emmet-vim', {'for': ['html', 'css']}
Plug 'junegunn/fzf' "{ 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim', {'for': ['markdown', 'text']}
"Plug 'davidhalter/jedi-vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree', {'on': ['NERDTreeToggle', 'NERDTreeFind']}
Plug 'zah/nim.vim'
Plug 'unblevable/quick-scope'
Plug 'luochen1990/rainbow'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'ervandew/supertab'
Plug 'dylnmc/synstack.vim' "{'on': ['SynAuto', 'SynAutoOn', 'SynPopup', 'SynPopupOn']}
Plug 'majutsushi/tagbar'
Plug 'wellle/targets.vim' "need this for cib to work from line beginning.
Plug 'SirVer/ultisnips'
Plug 'tpope/vim-abolish'
Plug 'alvan/vim-closetag', {'for': ['html, xhtml', 'phtml', 'xml']}
Plug 'kkoomen/vim-doge', {'for': ['python']}
Plug 'junegunn/vim-easy-align'
Plug 'tpope/vim-fugitive'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries', 'for': 'go'}
Plug 'xolox/vim-misc'
Plug 'fxn/vim-monochrome'
"Plug 'flebel/vim-mypy', { 'for': 'python', 'branch': 'bugfix/fast_parser_is_default_and_only_parser' }
Plug 'xolox/vim-notes'
"Plug 'junegunn/vim-peekaboo' "buggy mess
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'jremmen/vim-ripgrep'
Plug 'xolox/vim-session'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
"Plug 'jmcantrell/vim-virtualenv', {'for': ['python']}
Plug 'lervag/vimtex', {'for': ['tex']}
"Plug 'vimwiki/vimwiki'
cal plug#end()

pa! matchit

if !exists("g:os")
    if has("win64") || has("win32") || has("win16")
        let g:os = "Windows"
    else
        let g:os = substitute(system('uname'), '\n', '', '')
    endif
endif

function! s:ResizeNewWindow()
"    let l:max_line_length = max(map(range(1, line('$')), "virtcol([v:val, '$'])"))
"    let l:pref_min_line_length = 80
"    let l:offset = 10
"    "echom (s:max_line_length < s:pref_min_line_length ? s:pref_min_line_length : s:max_line_length)
"    "echom  max(map(range(1, line('$')), "virtcol([v:val, '$'])"))
"    "let &co=getline(1,'$')->map({ idx, val -> strchars(val) })->max()
"    let &co = (s:max_line_length < s:pref_min_line_length ?  s:pref_min_line_length : (s:max_line_length + s:offset))
endfun

function! s:PlugSort()
    let start = search('\v\C^%(^\s*"?\s*Plug)@!.*\n\zs', 'bcWn')
    let end = search('\v\C.\ze\n%(^\s*"?\s*Plug)@!', 'cW')
    exec start.','.end.'sort /^\s*"\?\s*Plug\s\+''[^\/]\+\// i'
    "echon 'plugins list sorted'
endfunction

if g:os =~ "Windows"
    cabbr :: !wsl
endif

se cursorline
se path+=**
se hlsearch
se nowrapscan
se enc=utf-8
se termguicolors
let ayucolor="dark"
se guifont=Anonymice_Powerline:h11:cANSI:qDRAFT

se pythonthreedll=python37.dll
"colo industry
let mapleader="\<Space>"

"if has('gui_running')
    "set list listchars=tab:▶‒,nbsp:∙,trail:∙,extends:▶,precedes:◀
    "let &showbreak = '↳'
"else
    "set list listchars=tab:>-,nbsp:.,trail:.,extends:>,precedes:<
    "let &showbreak = '^'
"endif

se ul=1000
se ai
se complete+=kspell
se si
se ar
se linebreak
se history=9999
se formatoptions+=r
se bs=indent,eol,start
se ts=4
se sts=4
se sw=4
se ttimeoutlen=10
"se ttimeout
se et
se fdl=99
se fdm=indent
"se gfn=Fira\ Mono\ for\ Powerline:h12
se hid
se ic
se scs
se is
se ls=2
se synmaxcol=300
se ttyfast
se lazyredraw
noh
se nowrap
se nu
se rnu
se nojoinspaces
se so=5
se shm+=Ia
se sc
se sm
se sr
se ruler
se bk
se udf
se ut=750
se wmnu
se bri

if !isdirectory(expand("~/.vim/tmp")) | cal mkdir(expand("~/.vim/tmp"), "p") | en
se dir=~/.vim/tmp//,.
se bdir=~/.vim/tmp//,.
se udir=~/.vim/tmp//,.
se undofile

"hush
se noeb novb t_vb=

se go-=m
se go-=T
se go-=r
se go-=L
se go+=c

se viminfo=!,h,'500
se viminfo+=<10000
se viminfo+=s1000
se viminfo+=/1000
se viminfo+=:1000

filetype plugin indent on
syn enable


if g:os =~ "Windows"
    nn <f12> :sil !ctags -R --python-kinds=-i %<cr>
elseif g:os =~ "Linux"
    nn <f12> :sil! !ctags -R --python-kinds=-i %<cr>
endif

noremap <expr> j (v:count? 'j' : 'gj')
noremap <expr> k (v:count? 'k' : 'gk')
function! s:ToggleDisplayLineMappings()
    if &wrap ==? 'nowrap'
        "unmap <silent> k
        "unmap <silent> j
        silent! unmap <silent> 0
        silent! unmap <silent> ^
        silent! unmap <silent> $
    else
        "no <silent> k gk
        "no <silent> j gj
        no <silent> 0 g0
        no <silent> ^ g^
        no <silent> $ g$
    endif
endfun

function! s:FixAyuColorScheme()
    if g:ayucolor==?'dark'
        highlight LineNr guifg=#808080
        highlight Normal ctermbg=NONE
        highlight Normal guibg=#000000
        highlight Comment guibg=#000000
        highlight String guibg=#000000

        highlight Search guibg=#ff8800 guifg=#000000
        "for hl_group in getcompletion('', 'highlight')
            "exe 'hi ' . hl_group . ' guibg=#000000 ctermbg=NONE'
        "endfor
    endif
endfun

function! s:FixCoqTailHL()
    "highlight CoqtailChecked guibg=#646258
    highlight CoqtailChecked guibg=#0b2042
    highlight CoqError guibg=#646258
    highlight MatchParen guibg=#000000
endfun

"function! AleDogePatch()
    "ALEDisable
    "call doge#generate()
    "ALEEnable
"endfun

no <Leader>a ggVG
no <silent> <Leader><Leader>w :se wrap!<CR>
no <silent> <Leader><Leader>h :se hls!<CR>
no <Leader>tt :w <C-R>=tempname()<CR>
nn <leader>ll :ALEToggle<CR>
"no <Leader>d call AleDogePatch()

nn <Leader>b :ls<CR>:b<Space>
nn <Leader>ff :BLines<CR>
nn <Leader>fh :History<CR>
sil! nm <F3> :NERDTreeFind<CR>
sil! nm <F4> :NERDTreeToggle<CR>
sil! nm <F8> :TagbarToggle<CR>

com! -nargs=* -complete=help H helpg <args>

ino <C-BS> <C-W>
cno <C-BS> <C-W>

xn < <gv
xn > >gv

nn <leader>n :Note<CR>
nn <silent> <Leader>e :e $MYVIMRC<CR>
nn <leader>w :w!<cr>
"nn <leader>w :up!<cr>
nn <leader>v :vs<CR><C-L><C-F>:se scb<CR><C-H>:se scb<CR>

"Windows-specific mappings

if g:os == "Windows"
    nn <leader>oe :sil! !start <C-R>='"' . expand("%:p:h") . '"'<CR><CR>
    nn <Leader>owe :!start Explorer /select,%:p<cr>
    nn <Leader>ocp :!start cmd /k cd %:p:h<cr>
endif

nn <leader>cp :let @*='"' . expand("%:p") . '"'<CR>
nn <leader>cd :let @*='"' . expand("%:p:h") . '"'<CR>
"TODO: disable in command mode history buffer.
nn <silent> <CR> :nohlsearch<CR>
nn <silent> <C-P> :FZF<CR>

nn <Leader>qo :cope<CR>
nn <Leader>qc :ccl<CR>
nn <Leader>lo :lop<CR>
nn <Leader>lc :lcl<CR>

nn <leader>ga :Git add %:p<CR><CR>
nn <leader>gs :Gstatus<CR>
nn <leader>gc :Gcommit -v -q<CR>
nn <leader>gt :Gcommit -v -q :%p<CR>
nn <leader>gd :Gdiff<CR>
nn <leader>ge :Gedit<CR>
nn <leader>gr :Gread<CR>
nn <leader>gw :Gwrite<CR><CR>
nn <leader>gl :sil! Glog<CR>:bot copen<CR>
nn <leader>gp :Ggrep<Space>
nn <leader>gm :Gmove<Space>
nn <leader>gb :Git branch<Space>
nn <leader>go :Git checkout<Space>
nn <leader>gps :Gpush<CR>
nn <leader>gpl :Gpull<CR>

nn <C-J> <C-W><C-J>
nn <C-K> <C-W><C-K>
nn <C-L> <C-W><C-L>
nn <C-H> <C-W><C-H>

nn <Left> <C-W><
nn <Right> <C-W>>
nn <Up> <C-W>+
nn <Down> <C-W>-

"No Ex mode ugh
"nn Q <nop>
nn Q @@


if isdirectory("C:/Users/User/Dropbox/VimNotes")
    let g:notes_directories = ["C:/Users/User/Dropbox/VimNotes"]
endif
"let g:notes_suffix = '.txt'

let g:colorizer_maxlines = 500

let g:vimtex_view_general_viewer = 'sumatrapdf'

let g:doge_doc_standard_python = 'numpy'
let g:session_autosave='yes'

let g:NERDTreeIgnore=['\.swp$', '\.un\~$', '\.pyc$', 'tags', '\.ropeproject[[dir]]', '__pycache__[[dir]]']
let g:NERDDefaultAlign = 'left'

let g:virtualenv_auto_activate=1

let g:user_emmet_install_global=0
let g:user_emmet_leader_key="<C-M>"

let g:tagbar_autofocus=1
let g:tagbar_compact=1
let g:tagbar_show_linenumbers=2
let g:tagbar_iconchars=['▶', '▼']
let g:tagbar_silent=1
let g:tagbar_sort=0
let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']

let g:rainbow_active=1

let g:session_autoload='no'

let g:ale_linters = {'python': ['flake8', 'mypy']}
let g:ale_fixers = {'*': ['remove_trailing_lines', 'trim_whitespace'], 'python': ['black', 'isort', 'add_blank_lines_for_python_control_statements']}
let g:ale_fix_on_save = 1
let g:ale_open_list = 1
nmap <silent> <a-k> <Plug>(ale_previous_wrap)
nmap <silent> <a-j> <Plug>(ale_next_wrap)
nmap <silent> <Leader>zww <Plug>VimwikiIndex

nmap <c-s> <plug>(SynStack)

func! s:SetBreakpoint()
    cal append('.', repeat(' ', strlen(matchstr(getline('.'), '^\s*'))) . 'import ipdb; ipdb.set_trace()')
endf

func! s:RemoveBreakpoint()
    exe 'sil! g/^\s*import\sipdb\;\?\n*\s*ipdb.set_trace()/d'
endf

func! s:ToggleBreakpoint()
    if getline('.')=~#'^\s*import\sipdb' | cal s:RemoveBreakpoint() | el | cal s:SetBreakpoint() | en
endf

cmap w!! %!sudo tee > /dev/null %

let g:tex_flavor = 'latex'
let g:coqtail_coq_path = 'C:\Coq\bin\'

function! s:Hardcopy()
  let colors_save = g:colors_name
  colorscheme default
  TOhtml
  execute 'colorscheme' colors_save
endfun

command! Hardcopy call s:Hardcopy()

aug all
    au!
    au BufWritePost $MYVIMRC nested so $MYVIMRC | cal s:PlugSort()
    au BufWritePost *.py sil !ctags %:h -R -V --python-kinds=-i

    if g:os == "Windows"
        au FileType python nn <buffer> <F5> :!start cmd /c python % & pause<cr>
        "au FileType python nn <buffer> <F5> :call system('python ' .
        "expand('%') . ' & pause')
    "elseif g:os =~ "linux"
    endif

    au FileType html,css EmmetInstall
    au FileType nerdtree setl rnu
    au FileType python nn <F6> :cal <SID>ToggleBreakpoint()<CR>
    "au GuiEnter * sim ~x "Maximized GVIM Window
    au QuickFixCmdPost * cw
    "au OptionSet nowrap cal DisableDisplayLineMappings()
    au OptionSet wrap cal s:ToggleDisplayLineMappings()
    "au VimEnter * call s:ResizeNewWindow()
    "au BufEnter * call s:ResizeNewWindow()
    au BufEnter * silent! lcd %:p:h
    "au BufWritePre * if &ft == '' | filetype detect | endif
aug END

aug CustomAyuColorScheme
    au!
    au ColorScheme ayu call s:FixAyuColorScheme()
aug END

aug CustomCoqTailHL
    au!
    au FileType coq CoqStart | call s:FixCoqTailHL()
aug END

"fallback to industry as an alternative to getting flashbanged...
try
    colorscheme ayu
catch
    colorscheme industry
endtry

"command! -bang -nargs=? -complete=dir Files call fzf#vim#files(<q-args>, {'options': ['--bind ctrl-b:preview-page-up, ctrl-f:preview-page-down']}, <bang>0)
"command! -bang -nargs=? -complete=dir BLines call fzf#vim#lines(<q-args>, {'options': ['--bind ctrl-b:preview-page-up, ctrl-f:preview-page-down']}, <bang>0)
"command! -bang -nargs=? -complete=dir History call fzf#vim#history(<q-args>, {'options': ['--bind ctrl-b:preview-page-up, ctrl-f:preview-page-down']}, <bang>0)

let g:pastebin = 'vpaste'

function! Pastebin(type)
    if a:type is# 'char'
        let l:regsave = getreg('"')
        normal! `[v`]y
        let l:text = split(getreg('"', "\n"))
        call setreg('"', l:regsave)
    elseif a:type is# 'line'
        let l:text = getline(line("'["), "']")
    elseif a:type is# 'v' || a:type is# "\<c-v>"
        let l:regsave = getreg('"')
        normal! gvy
        let l:text = split(@", "\n")
        call setreg('"', l:regsave)
    elseif a:type is# 'V'
        let l:text = getline(line("'<"), "'>")
    else
        let l:text = getline(line("'["), "']")
    endif
    let l:tmp = tempname()
    call writefile(l:text, l:tmp)
    call setreg('+', systemlist('sh -c ''curl -NsF "text=<'.l:tmp.'" vpaste.net?ft='.&ft.'''')[0] . '?bg=dark&nu')
    redraw!
    echon "\rDone: @+ = ".@+
endfunction

nnoremap <silent> <leader>pb :set opfunc=Pastebin<cr>g@
xnoremap <silent> <leader>pb :<c-u>call Pastebin(visualmode())<cr>

function! SourceLinesOfCodeWithoutComments()
    let l:smc = &l:smc
    let &l:smc=0
    let l:sloc = len(filter(range(line('$')), {idx -> synIDattr(synID(idx + 1, 1, 1), "name") !~? 'comment\|^$'}))
    let l:percent = str2float(printf("%.2f", str2float(l:sloc) / str2float(line("$")) * 100))
    echom l:sloc 'SLOC or ' . string(l:percent) . '% of the file is code (excluding empty lines and comments).'
    let &l:smc=l:smc
endfunction

nnoremap <silent> <leader>sloc :<c-u>call SourceLinesOfCodeWithoutComments()<cr>

command! SyntaxGroup :echo synIDattr(synID(line("."), col("."), 1), "name")
